doctrine:
    dbal:
        override_url: true
        url: '%env(resolve:DATABASE_URL)%'
        driver: pdo_sqlite
        host: localhost
        charset: utf8mb4
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/doctrine'
                prefix: 'App\Domain'
                alias: App
